apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx  # Corrected indentation
  ports:
  - protocol: TCP  # Corrected "protocal" to "protocol" and added "TCP"
    port: 80
    targetPort: 80
  type: ClusterIP  # Corrected "clusterip" to "ClusterIP"
